server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксирование запросов к API, если фронтенд и бэкенд на одном домене/порту
    # Если API на другом порту (как в docker-compose выше), то этот блок не нужен, 
    # так как в React мы указываем полный URL API.
}